baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '我的软件工坊'
theme = 'ananke'

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true


[languages]
  [languages.zh]
    title = "晖哥的软件工坊"
    weight = 1
    contentDir = "content/zh"
  

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  recent_posts_number = 3
  commentoEnable = false
  giscusEnable=true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"